include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: true
    sort_constructors_first: false
    prefer_single_quotes: true
    public_member_api_docs: false
    always_specify_types: false
    lines_longer_than_80_chars: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
